use raylib::prelude::Color;

#[derive(Clone, Copy, Debug)]
pub struct WindowTheme {
    pub padding_x: i32,
    pub padding_y: i32,
    pub titlebar_height: i32,
    pub resize_handle: i32,
    pub screen_padding: i32,
    pub title_font: i32,
    pub subtitle_font: i32,
    pub frame_color: Color,
    pub frame_shadow: Color,
    pub title_top: Color,
    pub title_bottom: Color,
    pub title_border: Color,
    pub body_color: Color,
    pub outline: Color,
    pub inner_outline: Color,
    pub title_text: Color,
    pub subtitle_text: Color,
    pub top_highlight: Color,
    pub resize_fill: Color,
    pub resize_outline: Color,
    pub resize_foreground: Color,
    pub title_hover_top: Color,
    pub title_hover_bottom: Color,
    pub resize_fill_hover: Color,
    pub resize_outline_hover: Color,
    pub tab_height: i32,
    pub tab_padding_x: i32,
    pub tab_padding_y: i32,
    pub tab_gap: i32,
    pub tab_strip_padding: i32,
    pub tab_content_spacing: i32,
    pub tab_font: i32,
    pub tab_min_width: i32,
    pub tab_strip_background: Color,
    pub tab_active_background: Color,
    pub tab_active_border: Color,
    pub tab_inactive_background: Color,
    pub tab_inactive_border: Color,
    pub tab_hover_background: Color,
    pub tab_hover_border: Color,
    pub tab_text_active: Color,
    pub tab_text_inactive: Color,
    pub tab_divider: Color,
    pub focus_outline: Color,
    pub focus_glow: Color,
    pub pinned_outline: Color,
    pub button_normal: Color,
    pub button_hover: Color,
    pub button_active: Color,
    pub button_icon: Color,
    pub button_icon_hover: Color,
    pub title_button_spacing: i32,
    pub title_button_size: i32,
}

impl Default for WindowTheme {
    fn default() -> Self {
        Self {
            padding_x: 18,
            padding_y: 16,
            titlebar_height: 34,
            resize_handle: 18,
            screen_padding: 10,
            title_font: 20,
            subtitle_font: 16,
            frame_color: Color::new(18, 22, 32, 235),
            frame_shadow: Color::new(6, 10, 18, 145),
            title_top: Color::new(66, 98, 154, 240),
            title_bottom: Color::new(48, 74, 116, 235),
            title_border: Color::new(24, 32, 48, 255),
            body_color: Color::new(16, 20, 30, 228),
            outline: Color::new(96, 114, 156, 200),
            inner_outline: Color::new(28, 36, 52, 210),
            title_text: Color::new(238, 244, 255, 255),
            subtitle_text: Color::new(188, 196, 214, 255),
            top_highlight: Color::new(158, 190, 242, 210),
            resize_fill: Color::new(24, 30, 44, 220),
            resize_outline: Color::new(48, 64, 92, 230),
            resize_foreground: Color::new(140, 176, 230, 220),
            title_hover_top: Color::new(82, 132, 198, 240),
            title_hover_bottom: Color::new(60, 110, 172, 235),
            resize_fill_hover: Color::new(36, 50, 72, 230),
            resize_outline_hover: Color::new(82, 108, 150, 240),
            tab_height: 32,
            tab_padding_x: 16,
            tab_padding_y: 6,
            tab_gap: 8,
            tab_strip_padding: 10,
            tab_content_spacing: 12,
            tab_font: 18,
            tab_min_width: 120,
            tab_strip_background: Color::new(22, 28, 40, 235),
            tab_active_background: Color::new(68, 108, 176, 240),
            tab_active_border: Color::new(28, 48, 78, 255),
            tab_inactive_background: Color::new(28, 36, 54, 228),
            tab_inactive_border: Color::new(42, 56, 78, 230),
            tab_hover_background: Color::new(52, 82, 134, 235),
            tab_hover_border: Color::new(62, 90, 138, 240),
            tab_text_active: Color::new(238, 244, 255, 255),
            tab_text_inactive: Color::new(188, 200, 220, 255),
            tab_divider: Color::new(32, 44, 66, 210),
            focus_outline: Color::new(110, 180, 255, 255),
            focus_glow: Color::new(50, 110, 200, 120),
            pinned_outline: Color::new(220, 184, 64, 240),
            button_normal: Color::new(24, 34, 52, 230),
            button_hover: Color::new(44, 68, 104, 240),
            button_active: Color::new(60, 96, 148, 255),
            button_icon: Color::new(220, 230, 245, 255),
            button_icon_hover: Color::new(244, 248, 255, 255),
            title_button_spacing: 6,
            title_button_size: 20,
        }
    }
}
