[[blocks]]
name = "air"
id = 0
solid = false
blocks_skylight = false
propagates_light = true
emission = 0
shape = "cube"
materials = { all = "unknown" }

[[blocks]]
name = "stone"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "stone" }

[[blocks]]
name = "sand"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "sand" }

[[blocks]]
name = "dirt"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "dirt" }

[[blocks]]
name = "grass"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "grass_top", bottom = "dirt", side = "grass_side" }

[[blocks]]
name = "snow"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "snow" }

[[blocks]]
name = "glowstone"
solid = true
blocks_skylight = true
emission = 15
shape = "cube"
materials = { all = "glowstone" }

[[blocks]]
name = "beacon"
solid = true
blocks_skylight = true
emission = 10
shape = "cube"
materials = { all = "beacon" }

# Logs (fixed vertical orientation)
[[blocks]]
name = "oak_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "oak_log_top", bottom = "oak_log_top", side = "oak_log" }

[[blocks]]
name = "birch_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "birch_log_top", bottom = "birch_log_top", side = "birch_log" }

[[blocks]]
name = "spruce_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "spruce_log_top", bottom = "spruce_log_top", side = "spruce_log" }

[[blocks]]
name = "jungle_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "jungle_log_top", bottom = "jungle_log_top", side = "jungle_log" }

[[blocks]]
name = "acacia_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "acacia_log_top", bottom = "acacia_log_top", side = "acacia_log" }

[[blocks]]
name = "dark_oak_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "oak_log_top", bottom = "oak_log_top", side = "oak_log" }

# Leaves
[[blocks]]
name = "oak_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "oak_leaves" }

[[blocks]]
name = "birch_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "birch_leaves" }

[[blocks]]
name = "spruce_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "spruce_leaves" }

[[blocks]]
name = "jungle_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "jungle_leaves" }

[[blocks]]
name = "acacia_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "acacia_leaves" }
