# Lighting behavior profiles (data-driven light modes)
[lighting.profiles.beam_cardinal]
mode = "beam"
straight_cost = 1
turn_cost = 32
vertical_cost = 32
source_dirs = "horizontal"

[[blocks]]
name = "air"
id = 0
solid = false
blocks_skylight = false
propagates_light = true
emission = 0
shape = "cube"
materials = { all = "unknown" }

[[blocks]]
name = "stone"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "stone" }

[[blocks]]
name = "sand"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "sand" }

[[blocks]]
name = "dirt"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "dirt" }

[[blocks]]
name = "grass"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "grass_top", bottom = "dirt", side = "grass_side" }

[[blocks]]
name = "snow"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { all = "snow" }

[[blocks]]
name = "glowstone"
solid = true
blocks_skylight = true
emission = 255
shape = "cube"
materials = { all = "glowstone" }

[[blocks]]
name = "beacon"
solid = true
blocks_skylight = true
# Beacon light is directional and attenuates slowly along cardinal paths.
# Set a strong source so it travels across chunks meaningfully.
emission = 200
shape = "cube"
materials = { all = "beacon" }
light_profile = "beam_cardinal"

# Common cubes (config-driven; replacing hardcoded enums)
[[blocks]]
name = "cobblestone"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "cobblestone" }

[[blocks]]
name = "mossy_cobblestone"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "mossy_cobblestone" }

[[blocks]]
name = "stone_bricks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "stone_bricks" }

[[blocks]]
name = "mossy_stone_bricks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "mossy_stone_bricks" }

[[blocks]]
name = "brick"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "brick" }

[[blocks]]
name = "granite"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "granite" }

[[blocks]]
name = "diorite"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "diorite" }

[[blocks]]
name = "andesite"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "andesite" }

[[blocks]]
name = "polished_granite"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "polished_granite" }

[[blocks]]
name = "polished_diorite"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "polished_diorite" }

[[blocks]]
name = "polished_andesite"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "polished_andesite" }

[[blocks]]
name = "gravel"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "gravel" }

[[blocks]]
name = "smooth_stone"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "smooth_stone" }

[[blocks]]
name = "sandstone"
solid = true
blocks_skylight = true
shape = "cube"
materials = { top = "sandstone_top", bottom = "sandstone_bottom", side = "sandstone_side" }

[[blocks]]
name = "red_sandstone"
solid = true
blocks_skylight = true
shape = "cube"
materials = { top = "red_sandstone_top", bottom = "red_sandstone_bottom", side = "red_sandstone_side" }

[[blocks]]
name = "quartz_block"
solid = true
blocks_skylight = true
shape = "cube"
materials = { top = "quartz_block_top", bottom = "quartz_block_top", side = "quartz_block_side" }

[[blocks]]
name = "lapis_block"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "lapis_block" }

[[blocks]]
name = "coal_block"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "coal_block" }

[[blocks]]
name = "prismarine_bricks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "prismarine_bricks" }

[[blocks]]
name = "nether_bricks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "nether_bricks" }

[[blocks]]
name = "end_stone"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "end_stone" }

[[blocks]]
name = "end_stone_bricks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "end_stone_bricks" }

[[blocks]]
name = "bookshelf"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "bookshelf" }

[[blocks]]
name = "coarse_dirt"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "coarse_dirt" }

[[blocks]]
name = "podzol"
solid = true
blocks_skylight = true
shape = "cube"
materials = { top = "podzol_top", bottom = "dirt", side = "podzol_side" }

# Slab (generic): half + material
[[blocks]]
name = "slab"
solid = true
blocks_skylight = true
emission = 0
shape = { kind = "slab", half = { from = "half" } }
state_schema = { half = ["bottom","top"], material = [
  "smooth_stone","sandstone","red_sandstone","cobblestone","mossy_cobblestone",
  "stone_bricks","mossy_stone_bricks","end_stone","end_stone_bricks","prismarine_bricks",
  "granite","diorite","andesite","polished_granite","polished_diorite","polished_andesite",
  "planks_oak","planks_birch","planks_spruce","planks_jungle","planks_acacia","planks_dark_oak",
  "quartz_block"
] }
[blocks.materials.top]
by = "material"
[blocks.materials.top.map]
smooth_stone = "smooth_stone"
sandstone = "sandstone_top"
red_sandstone = "red_sandstone_top"
cobblestone = "cobblestone"
mossy_cobblestone = "mossy_cobblestone"
stone_bricks = "stone_bricks"
mossy_stone_bricks = "mossy_stone_bricks"
end_stone = "end_stone"
end_stone_bricks = "end_stone_bricks"
prismarine_bricks = "prismarine_bricks"
granite = "granite"
diorite = "diorite"
andesite = "andesite"
polished_granite = "polished_granite"
polished_diorite = "polished_diorite"
polished_andesite = "polished_andesite"
planks_oak = "oak_planks"
planks_birch = "birch_planks"
planks_spruce = "spruce_planks"
planks_jungle = "jungle_planks"
planks_acacia = "acacia_planks"
planks_dark_oak = "oak_planks"
quartz_block = "quartz_block_top"

[blocks.materials.bottom]
by = "material"
[blocks.materials.bottom.map]
smooth_stone = "smooth_stone"
sandstone = "sandstone_bottom"
red_sandstone = "red_sandstone_bottom"
cobblestone = "cobblestone"
mossy_cobblestone = "mossy_cobblestone"
stone_bricks = "stone_bricks"
mossy_stone_bricks = "mossy_stone_bricks"
end_stone = "end_stone"
end_stone_bricks = "end_stone_bricks"
prismarine_bricks = "prismarine_bricks"
granite = "granite"
diorite = "diorite"
andesite = "andesite"
polished_granite = "polished_granite"
polished_diorite = "polished_diorite"
polished_andesite = "polished_andesite"
planks_oak = "oak_planks"
planks_birch = "birch_planks"
planks_spruce = "spruce_planks"
planks_jungle = "jungle_planks"
planks_acacia = "acacia_planks"
planks_dark_oak = "oak_planks"
quartz_block = "quartz_block_top"

[blocks.materials.side]
by = "material"
[blocks.materials.side.map]
smooth_stone = "smooth_stone"
sandstone = "sandstone_side"
red_sandstone = "red_sandstone_side"
cobblestone = "cobblestone"
mossy_cobblestone = "mossy_cobblestone"
stone_bricks = "stone_bricks"
mossy_stone_bricks = "mossy_stone_bricks"
end_stone = "end_stone"
end_stone_bricks = "end_stone_bricks"
prismarine_bricks = "prismarine_bricks"
granite = "granite"
diorite = "diorite"
andesite = "andesite"
polished_granite = "polished_granite"
polished_diorite = "polished_diorite"
polished_andesite = "polished_andesite"
planks_oak = "oak_planks"
planks_birch = "birch_planks"
planks_spruce = "spruce_planks"
planks_jungle = "jungle_planks"
planks_acacia = "acacia_planks"
planks_dark_oak = "oak_planks"
quartz_block = "quartz_block_side"

# Stairs (generic): half + facing + material
[[blocks]]
name = "stairs"
solid = true
blocks_skylight = true
emission = 0
shape = { kind = "stairs", half = { from = "half" }, facing = { from = "facing" } }
state_schema = { half = ["bottom","top"], facing = ["north","south","west","east"], material = [
  "planks_oak","planks_birch","planks_spruce","planks_jungle","planks_acacia","planks_dark_oak",
  "smooth_stone","cobblestone","mossy_cobblestone","stone_bricks","quartz_block","sandstone","red_sandstone"
] }
[blocks.materials.top]
by = "material"
[blocks.materials.top.map]
planks_oak = "oak_planks"
planks_birch = "birch_planks"
planks_spruce = "spruce_planks"
planks_jungle = "jungle_planks"
planks_acacia = "acacia_planks"
planks_dark_oak = "oak_planks"
smooth_stone = "smooth_stone"
cobblestone = "cobblestone"
mossy_cobblestone = "mossy_cobblestone"
stone_bricks = "stone_bricks"
quartz_block = "quartz_block_top"
sandstone = "sandstone_top"
red_sandstone = "red_sandstone_top"

[blocks.materials.bottom]
by = "material"
[blocks.materials.bottom.map]
planks_oak = "oak_planks"
planks_birch = "birch_planks"
planks_spruce = "spruce_planks"
planks_jungle = "jungle_planks"
planks_acacia = "acacia_planks"
planks_dark_oak = "oak_planks"
smooth_stone = "smooth_stone"
cobblestone = "cobblestone"
mossy_cobblestone = "mossy_cobblestone"
stone_bricks = "stone_bricks"
quartz_block = "quartz_block_top"
sandstone = "sandstone_bottom"
red_sandstone = "red_sandstone_bottom"

[blocks.materials.side]
by = "material"
[blocks.materials.side.map]
planks_oak = "oak_planks"
planks_birch = "birch_planks"
planks_spruce = "spruce_planks"
planks_jungle = "jungle_planks"
planks_acacia = "acacia_planks"
planks_dark_oak = "oak_planks"
smooth_stone = "smooth_stone"
cobblestone = "cobblestone"
mossy_cobblestone = "mossy_cobblestone"
stone_bricks = "stone_bricks"
quartz_block = "quartz_block_side"
sandstone = "sandstone_side"
red_sandstone = "red_sandstone_side"
# Logs (fixed vertical orientation)
[[blocks]]
name = "oak_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "oak_log_top", bottom = "oak_log_top", side = "oak_log" }

[[blocks]]
name = "birch_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "birch_log_top", bottom = "birch_log_top", side = "birch_log" }

[[blocks]]
name = "spruce_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "spruce_log_top", bottom = "spruce_log_top", side = "spruce_log" }

[[blocks]]
name = "jungle_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "jungle_log_top", bottom = "jungle_log_top", side = "jungle_log" }

[[blocks]]
name = "acacia_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "acacia_log_top", bottom = "acacia_log_top", side = "acacia_log" }

[[blocks]]
name = "dark_oak_log"
solid = true
blocks_skylight = true
emission = 0
shape = "cube"
materials = { top = "oak_log_top", bottom = "oak_log_top", side = "oak_log" }

# Leaves
[[blocks]]
name = "oak_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "oak_leaves" }

[[blocks]]
name = "birch_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "birch_leaves" }

[[blocks]]
name = "spruce_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "spruce_leaves" }

[[blocks]]
name = "jungle_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "jungle_leaves" }

[[blocks]]
name = "acacia_leaves"
solid = true
blocks_skylight = false
emission = 0
shape = "cube"
materials = { all = "acacia_leaves" }

# Planks as simple cubes
[[blocks]]
name = "oak_planks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "oak_planks" }

[[blocks]]
name = "birch_planks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "birch_planks" }

[[blocks]]
name = "spruce_planks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "spruce_planks" }

[[blocks]]
name = "jungle_planks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "jungle_planks" }

[[blocks]]
name = "acacia_planks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "acacia_planks" }

[[blocks]]
name = "dark_oak_planks"
solid = true
blocks_skylight = true
shape = "cube"
materials = { all = "oak_planks" }
