[package]
name = "geist-world"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
geist-blocks = { path = "../geist-blocks" }
fastnoise-lite = "1.1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
